---
- name: Install git and ruby dependencies
  apt: update_cache=yes pkg={{ item }} state=present
  become: yes
  with_items:
          - git-core
          - build-essential
          - zlib1g-dev
          - libreadline-dev
          - libssl-dev
          - libcurl4-openssl-dev
          - ruby-mysql
          - libmysqlclient-dev
  when: ansible_os_family == 'Debian'


- name: Install rbenv  locally
  become_user: "{{ user }}"
  become: yes
  git: repo=git://github.com/sstephenson/rbenv.git  dest="{{ rbenv_dir }}" accept_hostkey=True

- name:  Install ruby-build plugin
  become_user: "{{ user }}"
  become: yes
  git: repo=git://github.com/sstephenson/ruby-build.git  dest="{{ rbenv_plugins }}/ruby-build" accept_hostkey=True

- name: Touch your shell configuration file in case does not exist
  command: "/usr/bin/touch  creates={{home}}/.{{ sh }}rc"

- name: Add rbenv to path in your shell configuration file
  become_user: "{{ user }}"
  become: yes
  lineinfile: dest="{{ home }}/.{{ sh }}rc" line="export PATH=$HOME/.rbenv/bin:$PATH" state=present

- name: Custom .gemrc 
  copy: src=gemrc dest="{{ home }}/.gemrc" owner="{{ user }}" group="{{ user }}" mode=0644

- name: Custom .irbrc
  copy: src=irbrc dest="{{ home }}/.irbrc" owner="{{ user }}" group="{{ user }}" mode=0644

- name: Eval rbenv init
  become_user: "{{ user }}"
  become: yes
  lineinfile: dest="{{ home }}/.{{ sh }}rc" line="eval \"$(rbenv init -)\" " state=present

- name: Install ruby version
  become_user: "{{ user }}"
  become: yes
  command: "{{rbenv_dir}}/bin/rbenv install {{ ruby_version }}  creates={{ home }}/.rbenv/versions/{{ ruby_version }}"

- name: Enable ruby global version
  become_user: "{{ user }}"
  become: yes
  lineinfile: "dest={{ home }}/.rbenv/version line={{ ruby_version }} state=present create=yes" 


